### ISSUE TITLE
Violation of single responsibility principle in controllers/BrowseController.php

### ISSUE THREAD

**Issue by simon-rad** [Nastia-R/Vocabulary#5]
$email = $this->newWords->userEmail;

the newWords should not give any information about user email.
You should get user email from Models\Authorisation::getInstance()->getEmail()

**Comment by simon-rad** [comment]
There same for this part
Why does newWords has getUserIdByEmail method?

controllers/wordEditController.php

$email = Models\Authorisation::getInstance()->getEmail();
$userId = $newWords->getUserIdByEmail($email)->user_id;

**Comment by Nastia-R** [comment]
because i need to get user id by email in words model

**Comment by simon-rad** [comment]
But this is not a Words model controllers/wordEditController.php

this 

public function getUserIdByEmail($email)
  {
    $query = "SELECT user_id FROM users WHERE email = '$email'";
    $getUserIdStatement = $this->connection->query($query);
    $getUserId = $getUserIdStatement->fetch(PDO::FETCH_OBJ);
    return $getUserId;
  }

should be located in User model not in words model.

**Comment by Nastia-R** [comment]
now it is located in User model, but in Words model take place a creating of Users model's object and using Users methods=(
