### ISSUE TITLE
What is happening here?

### ISSUE THREAD

**Issue by simon-rad** [Nastia-R/Vocabulary#7]
What is happening here?

if($newUser->editUser($_GET['num'], $_POST['user'], $_POST['email']) != false)
{
    $warning = $newUser->editUser($_GET['num'], $_POST['user'], $_POST['email']);
}
else
{
    $edit_row = $newUser->getUser($_GET['num']);
    $msg = "Данные успешно обновлены!";
}

**Comment by Nastia-R** [comment]
oh, its because i changed checkOnRussian() to validateEmail() and now i use it in class User => method editUser(). there are stange construction that i created)

**Comment by Nastia-R** [comment]
its checking on validate email or not --- if false --- than all is ok=) coz i needed to return $warning and something else in another case, so i chose false..
